name: Purge image and stylesheet cache

on:
  push:
    branches: [ master ]

jobs:
  purge:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Purge cache
        uses: niwa-network/actions-cloudflare-purge@master
        if: success()
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          urls: https://niwanetwork.org/style.css
          prefixes: niwanetwork.org/images/logos/
